export EDITOR="nvim"

set -o vi

path()
{
  old=$IFS
  IFS=:
  printf "%s\n" $PATH
  ISF=$old
}

PS1='${debian_chroot:+($debian_chroot)}\[\033[02;36m\]$(__git_ps1)\[\033[00m\]:\[\033[03;33m\]\w\[\033[02;36m\]* \[\033[00m\]'
