set -o vi

path()
{
  old=$IFS
  IFS=:
  printf "%s\n" $PATH
  ISF=$old
}

function anybar { echo -n $1 | nc -4u -w0 localhost ${2:-1738}; }

source ~/.bash_aliases
source /usr/local/etc/bash_completion
source ~/.config/.git-prompt.sh

# if [ $ITERM_SESSION_ID ]; then
#   export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND";
# fi

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export PS1='$(__git_ps1 "(%s) ")\W > '

export PATH="/usr/local/sbin:$PATH"
export PATH=${PATH}:${HOME}/.bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export JAVA_HOME=$(/usr/libexec/java_home)

export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

export PATH=${PATH}:${HOME}/.composer/vendor/bin
export PATH=${PATH}:${HOME}/work/soft/apache-maven-3.5.2/bin

export PATH=${PATH}:${HOME}/work/soft/flutter/bin

export REACT_EDITOR=nvim

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

export PYENV_ROOT=${HOME}/.pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/admin/Downloads/google-cloud-sdk/path.bash.inc' ]; then source '/Users/admin/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/admin/Downloads/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/admin/Downloads/google-cloud-sdk/completion.bash.inc'; fi

