alias gil="git log --oneline --graph --decorate --all"
alias gis="git status"
alias gia="git add -A"

alias v="nvim"
alias n="DARK_BG=1 nvim"
alias nvim-config="nvim ~/.config/nvim/init.vim"

alias t="tmux"
alias ks-tmux="tmux kill-session"

alias ya="yarn add"
alias yad="yarn add --dev"
alias yarm="yarn remove"
alias yaui="yarn upgrade-interactive"

alias dm="adb shell input keyevent 82"
alias adb-reverse="adb reverse tcp:8081 tcp:8081"

alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -alh"
alias la="ls -A"
alias tl="tree -CL 1"
alias d="cd ~"
alias c="clear"
