---
- hosts: localhost
  connection: local

  tasks:
    - name: Link dotfiles to $HOME
      file: src=~/dotfiles/files/{{ item }}
            dest=~/.{{ item }}
            state=link
            force=yes
      with_items:
        - bash_aliases
#        - bash_profile
        - gitconfig
        - tmux.conf
