---
- hosts: all
  tasks:
    - apt: name={{ item }} state=latest update_cache=yes
      become: yes
      with_items:
        - vim-nox
        - ack-grep
        - exuberant-ctags
        - curl

    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items:
        - vimrc

    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim

    - command: vim -i NONE -c PluginUpdate -c quitall
      tags: update

    - command: make chdir=~/.vim/bundle/vimproc.vim/
